### ISSUE TITLE
Data set 

### ISSUE THREAD

**Issue by TehreemZainab** [ucrbioinfo/DeeplyEssential#1]
DEG link is not working . Can you please share link from where I can get dataset for this code.

**Comment by mdahasan** [comment]
It seems like the link is not working anymore. However, I have the dataset downloaded. Please let me know if you want the dataset. I can share it with you. Also, you can download a similar dataset from [OGEE](http://ogee.medgenius.info/browse/)

**Comment by TehreemZainab** [comment]
OGEE categorize locus as essential and non-essential. I would highly appreciate if you can share data as required  for parameters 1, 2 and 4.

**Comment by mdahasan** [comment]
You can download the data from [Here](https://drive.google.com/open?id=1pSSlc3LkYJRvNY9zXrcCsXvLf3wwTh3w)
